##################################################################
# VS Code with REST Client extension is needed to use this file.
# Download at: https://aka.ms/vscode/rest-client
##################################################################

@api_host = http://localhost:7072

### Get access token, should return 401
GET {{api_host}}/api/me/access-token

### Get access token
GET {{api_host}}/api/me/access-token
x-ms-client-principal: eyJ1c2VySWQiOiJfX3Rlc3RfdXNlcl9fIn0=
